# Generated by Django 3.0.7 on 2020-11-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20200628_2328"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="twitter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
